#!/bin/bash

processors=$processors
tmpdir=$(mktemp -d)
destfile=$2

if [ -z "$destfile" ]
then
	destfile=${1//\//_}.tar.xz
fi

if [ -z "$processors" ]
then
	processors=$(cat /proc/cpuinfo | grep "processor" | wc -l)
fi

make -j $processors -C $1 DESTDIR=$tmpdir install
tar -C $tmpdir --anchored -c ./ | xz > $destfile

rm -rf $tmpdir
make -C $1 clean

