#!/bin/bash

processors=$processors
tmpdir=$(mktemp -d)
destfile=${2:-${1//\//_}.tar.xz}
processors=${processors:-$(cat /proc/cpuinfo | grep "processor" | wc -l)}
package=$1
cleanup=${cleanup:-yes}

[ -z "$package" ] && echo "Usage: pkg_package PACKAGE [DEST]" && exit 2

if [ ! -d "$package" ]
then
	echo "$package not found" 2>/dev/null
	exit 1
fi

if [ -n "$PREFIX" ]
then
	flags="$flags PREFIX=\"${PREFIX}\""
fi

make -j $processors -C $1 DESTDIR=$tmpdir $flags install
if [ $? != 0 ]
then
	echo "Failure" 2>/dev/null
	rm -rf $tmpdir
	[ "$cleanup" == "yes" ] && make -C $1 clean
	exit 1
fi

tar -C $tmpdir --anchored -c ./ | xz > $destfile

rm -rf $tmpdir
[ "$cleanup" == "yes" ] && make -C $1 clean

