PACKAGES := xf86-input-evdev font-util mkfontscale mkfontdir bdftopcf fonts-alias fonts-encodings fonts-misc setxkbmap kbproto xcb-proto libxcb libx11 libxkbfile xkbcomp xkeyboard-config server libxau pixman libdrm libpciaccess fontsproto libfontenc libxfont xproto libxdmcp
.PHONY: $(PACKAGES) bootstrap

bootstrap: | $(PACKAGES)

$(PACKAGES):
	-$(MAKE) -C $@ install DESTDIR=$(DESTDIR)

